### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by bjw34032** [dayoonkwon/BioAge#19]
Thanks for making this package available!  

I run into the following error 
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘flexsurv’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

when executing `devtools::install_github("dayoonkwon/BioAge")`.  Maybe the package `flexsurv` should be moved to the Depends category instead of the Suggests category in DESCRIPTION file?  Could also be due to the fact that I'm using the latest version of R.

My environment is 
```
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts       
```

Thanks, Brandon

**Comment by bjw34032** [comment]
Same problem with packages: `htmlTable` and `survey`.

**Comment by dayoonkwon** [comment]
Hi Brandon,

To resolve the error, you should install the "flexsurv," "htmlTable," and "survey" packages using the install.packages() function if you haven't already done so. Then, you can use the "BioAge" package without explicitly loading the suggested packages. The "BioAge" package should automatically detect and use them when needed.

Since these packages are in the "Suggests" category, you do not have to load them manually unless you want to use specific functions or features from those packages directly.

Thank you,
Dayoon
